const char *clang_format =
	"Language:        Cpp\n"
	"# BasedOnStyle:  Chromium\n"
	"AccessModifierOffset: -1\n"
	"AlignAfterOpenBracket: Align\n"
	"AlignConsecutiveAssignments: false\n"
	"AlignConsecutiveDeclarations: false\n"
	"AlignEscapedNewlines: Right\n"
	"AlignOperands:   true\n"
	"AlignTrailingComments: true\n"
	"AllowAllParametersOfDeclarationOnNextLine: false\n"
	"AllowShortBlocksOnASingleLine: false\n"
	"AllowShortCaseLabelsOnASingleLine: false\n"
	"AllowShortFunctionsOnASingleLine: None\n"
	"AllowShortIfStatementsOnASingleLine: false\n"
	"AllowShortLoopsOnASingleLine: false\n"
	"AlwaysBreakAfterDefinitionReturnType: None\n"
	"AlwaysBreakAfterReturnType: None\n"
	"AlwaysBreakBeforeMultilineStrings: true\n"
	"AlwaysBreakTemplateDeclarations: true\n"
	"BinPackArguments: true\n"
	"BinPackParameters: true\n"
	"BraceWrapping:\n"
	"  AfterClass:      false\n"
	"  AfterControlStatement: false\n"
	"  AfterEnum:       false\n"
	"  AfterFunction:   false\n"
	"  AfterNamespace:  false\n"
	"  AfterObjCDeclaration: false\n"
	"  AfterStruct:     false\n"
	"  AfterUnion:      false\n"
	"  BeforeCatch:     false\n"
	"  BeforeElse:      false\n"
	"  IndentBraces:    false\n"
	"  SplitEmptyFunction: true\n"
	"  SplitEmptyRecord: true\n"
	"  SplitEmptyNamespace: true\n"
	"BreakBeforeBinaryOperators: None\n"
	"BreakBeforeBraces: Custom\n"
	"BreakBeforeInheritanceComma: false\n"
	"BreakBeforeTernaryOperators: true\n"
	"BreakConstructorInitializersBeforeComma: false\n"
	"BreakConstructorInitializers: BeforeColon\n"
	"BreakAfterJavaFieldAnnotations: false\n"
	"BreakStringLiterals: true\n"
	"ColumnLimit:     100\n"
	"CommentPragmas:  '^ IWYU pragma:'\n"
	"CompactNamespaces: false\n"
	"ConstructorInitializerAllOnOneLineOrOnePerLine: true\n"
	"ConstructorInitializerIndentWidth: 4\n"
	"ContinuationIndentWidth: 4\n"
	"Cpp11BracedListStyle: true\n"
	"DerivePointerAlignment: false\n"
	"DisableFormat:   false\n"
	"ExperimentalAutoDetectBinPacking: false\n"
	"FixNamespaceComments: true\n"
	"ForEachMacros:\n"
	"  - foreach\n"
	"  - Q_FOREACH\n"
	"  - BOOST_FOREACH\n"
	"IncludeCategories:\n"
	"  - Regex:           '^<.*\\.h>'\n"
	"    Priority:        1\n"
	"  - Regex:           '^<.*'\n"
	"    Priority:        2\n"
	"  - Regex:           '.*'\n"
	"    Priority:        3\n"
	"IncludeIsMainRegex: '([-_](test|unittest))?$'\n"
	"IndentCaseLabels: true\n"
	"IndentWidth:     4\n"
	"IndentWrappedFunctionNames: false\n"
	"JavaScriptQuotes: Leave\n"
	"JavaScriptWrapImports: true\n"
	"KeepEmptyLinesAtTheStartOfBlocks: false\n"
	"MacroBlockBegin: ''\n"
	"MacroBlockEnd:   ''\n"
	"MaxEmptyLinesToKeep: 1\n"
	"NamespaceIndentation: None\n"
	"ObjCBlockIndentWidth: 4\n"
	"ObjCSpaceAfterProperty: false\n"
	"ObjCSpaceBeforeProtocolList: false\n"
	"PenaltyBreakAssignment: 200\n"
	"PenaltyBreakBeforeFirstCallParameter: 1\n"
	"PenaltyBreakComment: 300\n"
	"PenaltyBreakFirstLessLess: 120\n"
	"PenaltyBreakString: 1000\n"
	"PenaltyExcessCharacter: 1000000\n"
	"PenaltyReturnTypeOnItsOwnLine: 200\n"
	"PointerAlignment: Right\n"
	"ReflowComments:  true\n"
	"SortIncludes:    false\n"
	"SortUsingDeclarations: true\n"
	"SpaceAfterCStyleCast: false\n"
	"SpaceAfterTemplateKeyword: true\n"
	"SpaceBeforeAssignmentOperators: true\n"
	"SpaceBeforeParens: ControlStatements\n"
	"SpaceInEmptyParentheses: false\n"
	"SpacesBeforeTrailingComments: 2\n"
	"SpacesInAngles:  false\n"
	"SpacesInContainerLiterals: true\n"
	"SpacesInCStyleCastParentheses: false\n"
	"SpacesInParentheses: false\n"
	"SpacesInSquareBrackets: false\n"
	"Standard:        Auto\n"
	"TabWidth:        4\n"
	"UseTab:          Always";