name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest", artifact: "Windows.7z",
            os: windows-latest
          }
          - {
            name: "Ubuntu Latest GCC", artifact: "Linux.7z",
            os: ubuntu-latest
          }

    steps:
    - uses: actions/checkout@v2

    - name: Install SDL2 and SDL2_image on Windows
      if: ${{ runner.os == 'Windows'}}
      run: |
        mkdir SDL2
        cd SDL2
        
        curl -o SDL2.zip https://www.libsdl.org/release/SDL2-devel-2.0.20-VC.zip
        curl -o SDL2_image.zip https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip
        
        Expand-Archive SDL2.zip .
        Expand-Archive SDL2_image.zip .
      
        set PATH="%PATH%;${{github.workspace}}\SDL2\SDL2-2.0.20;${{github.workspace}}\SDL2\SDL2_image-2.0.5"
      
        cd ..

    - name: Install SDL2 and SDL2_image on Linux
      if: ${{ runner.os == 'Linux'}}
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-image-dev
        mkdir SDL2
        cd SDL2
        wget https://www.libsdl.org/release/SDL2-2.0.20.tar.gz
        tar -xzf SDL2-2.0.20.tar.gz
        cd SDL2-2.0.20
        ./configure
        make all -j
        sudo make install
        cd ../..

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.config.artifact}}
        path: |
          ${{github.workspace}}/build/ngine
          ${{github.workspace}}/build/ngine.exe
          ${{github.workspace}}/build/montserrat.ttf