name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest", artifact: "Windows",
            os: windows-latest,
            cc: "C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-gcc.exe",
            cxx: "C:/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin/x86_64-w64-mingw32-g++.exe"
          }
          - {
            name: "Ubuntu Latest GCC", artifact: "Linux",
            os: ubuntu-latest,
            cc: "gcc", cxx: "g++"
          }

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up MinGW on Windows
        uses: conradhuebler/setup-mingw@master
        if: ${{ runner.os == 'Windows'}}
        with:
          platform: x64

      - name: Install SDL2 and SDL2_image on Windows
        if: ${{ runner.os == 'Windows'}}
        run: |
          mkdir SDL2
          cd SDL2
          
          curl -s https://www.libsdl.org/release/SDL2-devel-2.0.20-mingw.tar.gz -O SDL2-devel-2.0.20-mingw.tar.gz
          curl -s https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-mingw.tar.gz -O SDL2_image-devel-2.0.5-mingw.tar.gz
          
          tar -xzf SDL2-devel-2.0.20-mingw.tar.gz
          tar -xzf SDL2_image-devel-2.0.5-mingw.tar.gz
          
          cd SDL2-2.0.20
          make native
          cd ..
          
          cd SDL2_image-2.0.5
          make native
          cd ..
          
          cd ..

      - name: Install SDL2 and SDL2_image on Linux
        if: ${{ runner.os == 'Linux'}}
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-image-dev
          mkdir SDL2
          cd SDL2
          wget https://www.libsdl.org/release/SDL2-2.0.20.tar.gz
          tar -xzf SDL2-2.0.20.tar.gz
          cd SDL2-2.0.20
          ./configure
          make all -j
          sudo make install
          cd ../..

      - name: Configure CMake
        shell: cmake -P {0}
        run: |
          if(UNIX)
            execute_process(COMMAND cmake -S . -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=$ENV{BUILD_TYPE})
          else()
            execute_process(COMMAND cmake -S . -B D:/a/ngine/ngine/build -D CMAKE_BUILD_TYPE=$ENV{BUILD_TYPE} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -G "MinGW Makefiles")
          endif()

      - name: Build
        run: |
          set SDL2DIR="${{github.workspace}}\SDL2"
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.artifact}}
          path: |
            ${{github.workspace}}/build/ngine
            ${{github.workspace}}/build/ngine.exe
            ${{github.workspace}}/build/montserrat.ttf
            ${{github.workspace}}/build/sheet.png
            ${{github.workspace}}/build/sheet.json
            ${{github.workspace}}/build/*.dll
