name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows Latest", artifact: "Windows.7z",
            os: windows-latest
          }
          - {
            name: "Ubuntu Latest GCC", artifact: "Linux.7z",
            os: ubuntu-latest
          }

    steps:
      - uses: actions/checkout@v2

      - name: Install SDL2 and SDL2_image on Windows
        if: ${{ runner.os == 'Windows'}}
        run: |
          vcpkg install sdl2
          vcpkg install sdl2-image
#          mkdir download
#          cd download
#          curl -o SDL2.zip https://www.libsdl.org/release/SDL2-devel-2.0.20-VC.zip
#          curl -o SDL2_image.zip https://www.libsdl.org/projects/SDL_image/release/SDL2_image-devel-2.0.5-VC.zip
#
#          Expand-Archive SDL2.zip .
#          Expand-Archive SDL2_image.zip .
#
#          cd ..
#
#          xcopy download\SDL2-2.0.20\include\ SDL2\include\SDL2\
#          xcopy download\SDL2-2.0.20\lib\x64\ SDL2\bin\
#          xcopy download\SDL2-2.0.20\lib\x64\ SDL2\lib\
#
#          xcopy download\SDL2_image-2.0.5\include\ SDL2\include\SDL2\
#          xcopy download\SDL2_image-2.0.5\lib\x64\ SDL2\bin\
#          xcopy download\SDL2_image-2.0.5\lib\x64\ SDL2\lib\

      - name: Install SDL2 and SDL2_image on Linux
        if: ${{ runner.os == 'Linux'}}
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-image-dev
          mkdir SDL2
          cd SDL2
          wget https://www.libsdl.org/release/SDL2-2.0.20.tar.gz
          tar -xzf SDL2-2.0.20.tar.gz
          cd SDL2-2.0.20
          ./configure
          make all -j
          sudo make install
          cd ../..

      - name: Configure CMake
        run: |
          set SDL2DIR="${{github.workspace}}\SDL2"
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          set SDL2DIR="${{github.workspace}}\SDL2"
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.config.artifact}}
          path: |
            ${{github.workspace}}/build/ngine
            ${{github.workspace}}/build/ngine.exe
            ${{github.workspace}}/build/montserrat.ttf